// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnzW27A0m2GbDSfxOVLpsbQFpN64iNQV8',
    appId: '1:469072988532:web:d620bed00e1ec807524421',
    messagingSenderId: '469072988532',
    projectId: 'smart-threads-860de',
    authDomain: 'smart-threads-860de.firebaseapp.com',
    storageBucket: 'smart-threads-860de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt2Eju-EtNR2t3RMw2QbJElAzhg0T9mgw',
    appId: '1:469072988532:android:2af9113fd60bf34b524421',
    messagingSenderId: '469072988532',
    projectId: 'smart-threads-860de',
    storageBucket: 'smart-threads-860de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVHPufdfgZrCJe-6pcwlbnSPX4BlYvMv0',
    appId: '1:469072988532:ios:5ac839ff038d91aa524421',
    messagingSenderId: '469072988532',
    projectId: 'smart-threads-860de',
    storageBucket: 'smart-threads-860de.firebasestorage.app',
    iosBundleId: 'com.example.smartThreads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVHPufdfgZrCJe-6pcwlbnSPX4BlYvMv0',
    appId: '1:469072988532:ios:5ac839ff038d91aa524421',
    messagingSenderId: '469072988532',
    projectId: 'smart-threads-860de',
    storageBucket: 'smart-threads-860de.firebasestorage.app',
    iosBundleId: 'com.example.smartThreads',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnzW27A0m2GbDSfxOVLpsbQFpN64iNQV8',
    appId: '1:469072988532:web:a0ee6e8bb11b4c8e524421',
    messagingSenderId: '469072988532',
    projectId: 'smart-threads-860de',
    authDomain: 'smart-threads-860de.firebaseapp.com',
    storageBucket: 'smart-threads-860de.firebasestorage.app',
  );
}
